title: Double Great
description: "Web projects made in Upstate New York."
url: "https://doublegreat.dev"
remote_theme: double-great/great-great-jekyll-theme@main
github: double-great
permalink: pretty
collections:
  projects:
    output: true
header_pages:
  - drafts.md
  - colophon.md
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

exclude:
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - Gemfile
  - Gemfile.lock
  - .github
  - library.dic
  - vendor
